### ISSUE TITLE
Create a game that plays against a hosted AI

### ISSUE THREAD

**Issue by mmmries** [mmmries/ref#2]
When creating a game it would be cool if you could ask `ref` to play against you, so you didn't have to get your own opponent lined up.

Maybe you could pick between letting a human play, playing against `ref`'s AI or just leaving the game private and sending a link to your opponent?

**Comment by film42** [comment]
I really like the idea of each game having its own AI. Let's make it happen. :clap: :clap: 

Even if it's only to show "the game works," I think it's a worthwhile addition.

**Comment by mmmries** [comment]
I've got a decent start down this path going in the `hosted_ai` branch, but I just ran into something that I'm not sure how I want to solve.

Right now the channel notices that the game creator asked for an AI opponent and it just spawns off a GenServer that will join the game and make moves. But the problem is that when the `Random` genserver makes a move, the new game state never gets broadcasted.

Right now the Channel is responsible for proxying requests to the game and based on the response from the game it decides what to publish. But now there are two different processes interacting with the game, should they both publish things (lots of duplication here?) or should the TicTacToe game be responsible for publishing updates?

**Comment by mmmries** [comment]
I switched around a few things and got it working in a very "hacky" way. The game now publishes its own updates except when people join the game, because we want to finish their registration to the channel before we broadcast.  In that case the channel handles the broadcast. This split between when the channel and when the game broadcast stuff is the hacky bit.

Other than that this is now functional and I can ship it.

a72be58b6f89df76096a172e1d0c30e12634c812
